spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        #spring.json.trusted.packages: com.josmaria.SpringSecEx.payload
        #spring.json.trusted.packages: com.josmaria.SpringSecEx.payload, com.josmaria.SpringSecEx.domain
        spring.json.trusted.packages: '*'
